# Generated by Django 4.2.7 on 2023-11-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("rating", models.FloatField(default=0.0)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="security.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("business_name", models.CharField(max_length=32)),
                ("description", models.TextField()),
                ("phone_number", models.CharField(max_length=9)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("work_time", models.CharField(max_length=11)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviews", models.ManyToManyField(blank=True, to="api.review")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="security.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=32)),
                ("pictures", models.TextField()),
                ("description", models.TextField()),
                ("price", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(choices=[("00", "Food & Drinks")], max_length=2),
                ),
                ("rating", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.serviceprovider",
                    ),
                ),
                ("reviews", models.ManyToManyField(blank=True, to="api.review")),
            ],
        ),
    ]
