# Generated by Django 4.2.7 on 2023-11-26 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_geolocation_serviceprovider_geolocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geolocation",
            name="longitude",
        ),
    ]
