# Generated by Django 4.2.7 on 2023-11-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_serviceprovider_geolocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistoryentry",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
