# Generated by Django 4.2.7 on 2023-11-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=128)),
                ("salt", models.CharField(max_length=4)),
                ("birth_date", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "profile_picture",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("A", "Admin"), ("P", "Provider"), ("G", "Guest")],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
